### ISSUE TITLE
Unable to convert current line to heading

### ISSUE THREAD

**Issue by asika32764** [editor-js/header#114]
Test on last CDN version.

![header](https://github.com/editor-js/header/assets/1639206/ed507f03-cb2c-464e-8560-a7abb8c0399a)

**Comment by CasFreriks** [comment]
Did you find a fix for this problem? I have the exact same issue right now.

**Comment by TontonSancho** [comment]
Same here.

But,
I may have figured out where the problem comes from:

- Header code [includes conversionConfig](https://github.com/editor-js/header/blob/64a4a023647530e343c37fb8669059c57c8a0c74/src/index.ts#L254) : :heavy_check_mark: 
- Header constructor receives converted text [as crud data](https://github.com/editor-js/header/blob/64a4a023647530e343c37fb8669059c57c8a0c74/src/index.ts#L101)
- Header constructor [normalizes data](https://github.com/editor-js/header/blob/64a4a023647530e343c37fb8669059c57c8a0c74/src/index.ts#L119) before storing it : :heavy_check_mark:
- Normalize data [checks for compatible data](https://github.com/editor-js/header/blob/64a4a023647530e343c37fb8669059c57c8a0c74/src/index.ts#L161) : :heavy_check_mark: 
- Validation fails : Header [considers valid data](https://github.com/editor-js/header/blob/64a4a023647530e343c37fb8669059c57c8a0c74/src/index.ts#L147) to contain `text` **AND** `level` : :x: 

Since the Header block new instance comes from a conversion, the conversion provides only `text` parameter.

**Comment by neSpecc** [comment]
Resolved by #116
